# Generated by Django 4.2.7 on 2024-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('cedula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('numero', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('localidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_colaborador', models.IntegerField()),
                ('id_emergencia', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
