# Generated by Django 5.1.2 on 2024-10-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='numero',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='app_administrador',
        ),
        migrations.AlterModelTable(
            name='colaborador',
            table='app_colaborador',
        ),
        migrations.AlterModelTable(
            name='seguimiento',
            table='app_seguimiento',
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('act', models.BooleanField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
            ],
            options={
                'verbose_name': 'Emergencia',
                'verbose_name_plural': 'Emergencias',
                'db_table': 'app_emergencia',
            },
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_emergencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emergencia'),
        ),
    ]
