# Generated by Django 5.1.2 on 2024-10-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localdiades',
            },
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='estado',
        ),
    ]
