# Generated by Django 5.1.2 on 2024-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emergencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seguimiento',
            options={},
        ),
        migrations.RemoveField(
            model_name='emergencia',
            name='id_administrador',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='id_serv',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='id_administrado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='pagina',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='users',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='act',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_colaborador',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_emergencia',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table=None,
        ),
        migrations.AlterModelTable(
            name='colaborador',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emergencia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='localidad',
            table=None,
        ),
        migrations.AlterModelTable(
            name='seguimiento',
            table=None,
        ),
    ]
